export const ALL_EMPLOYEE_REQUEST="ALL_EMPLOYEE_REQUEST";
export const ALL_EMPLOYEE_SUCCESS="ALL_EMPLOYEE_SUCCESS";
export const ALL_EMPLOYEE_FAIL="ALL_EMPLOYEE_FAIL";

export const EMPLOYEE_DETAILS_REQUEST="EMPLOYEE_DETAILS_REQUEST";
export const EMPLOYEE_DETAILS_SUCCESS="EMPLOYEE_DETAILS_SUCCESS";
export const EMPLOYEE_DETAILS_FAIL="EMPLOYEE_DETAILS_FAIL";

export const EMPLOYEE_CREATE_REQUEST="EMPLOYEE_CREATE_REQUEST";
export const EMPLOYEE_CREATE_SUCCESS="EMPLOYEE_CREATE_SUCCESS";
export const EMPLOYEE_CREATE_FAIL="EMPLOYEE_CREATE_FAIL";

export const EMPLOYEE_UPDATE_REQUEST="EMPLOYEE_UPDATE_REQUEST";
export const EMPLOYEE_UPDATE_SUCCESS="EMPLOYEE_UPDATE_SUCCESS";
export const EMPLOYEE_UPDATE_FAIL="EMPLOYEE_UPDATE_FAIL";

export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"


export const CLEAR_ERRORS="CLEAR_ERRORS";
